apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustersecret
spec:
  source:
    repoURL: "https://charts.clustersecret.com/"
    targetRevision: "0.4.3"
    chart: clustersecret
    helm:
      releaseName: clustersecret
  project: "default"
  destination:
    server: https://kubernetes.default.svc
    namespace: "clustersecret"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
